---

#- hosts: pull_mode_hosts
#  remote_user: ubuntu
#  sudo: yes
#  tasks:
#  - name: add official nginx repository
#    apt_repository: repo='deb http://nginx.org/packages/ubuntu/ trusty nginx' state=present

#  - name: ansible pull install nginx web server and ensure its at the latest version
#    apt: name=nginx state=latest force=yes

#  - name: ansible pull install nmap
#    apt: name=nmap state=present


- hosts: pull_mode_hosts
  remote_user: ubuntu
  sudo: yes
  tasks:

    - name: remove official nginx repository
      apt_repository: repo='deb http://nginx.org/packages/ubuntu/ trusty nginx' state=absent

    - name: ansible pull install build-essential
      apt: name=build-essential state=present

    - name: ansible pull install curl
      apt: name=curl state=present

    - name: ansible pull install git
      apt: name=git state=present

    - name: ansible pull install python
      apt: name=python state=present

    - name: ansible pull install nodejs
      apt: name=nodejs state=present

    - name: ansible pull install npm
      apt: name=npm state=present

    - name: ansible pull install forever daemon
      npm: name=forever global=yes state=latest

    - name: create symlink for node
      file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

    - name: known_hosts
      shell: touch ~/.ssh/known_hosts

    - name: remove github.com from known host
      shell: ssh-keygen -R bitbucket.org

    - name: ensure github.com in known host
      shell: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    - name: create app directory
      file: path=/opt/app/ state=directory mode=0755

    - name: git clone app repo
      git: repo=git@bitbucket.org:arquiteturacloudteam/source_code_app.git dest=/opt/app/ key_file=/etc/ansible/ansible_pull update=yes clone=yes

    - name: install packages based on package.js
      npm: path=/opt/app/package.json state=present

    - name: "Check list of Node.js apps running."
      command: forever list
      register: forever_list
      changed_when: false

    - name: "Start example Node.js app."
      command: forever start test_server.js
      when: "forever_list.stdout.find('/opt/app/server.js') == -1"
