---
- hosts: pull_mode_hosts
  remote_user: ubuntu
  connection: local
  sudo: yes
  tasks:

    - name: ansible pull install build-essential
      apt: name=build-essential state=present

    - name: ansible pull install curl
      apt: name=curl state=present

    - name: ansible pull install git
      apt: name=git state=present

    - name: ansible pull install python
      apt: name=python state=present

    - name: create app directory
      file: path=/opt/deploy/ state=directory mode=0755 owner=root group=root

    - name: git clone app repo
      git: |
        repo=git@bitbucket.org:arquiteturacloudteam/source_code_app.git
        dest=/opt/deploy/ key_file=/etc/ansible/ansible_pull
        accept_hostkey=yes update=yes force=yes

    - name: change directory
      shell: cd /opt/deploy/

    - name: execute Docker compose
      shell: docker-compose up chdir=/opt/deploy

    - name: docker-compose ps
      shell: docker-compose ps
