---

- hosts: pull_mode_hosts
  remote_user: ubuntu
  sudo: yes

- name: add official nginx repository
  apt_repository: repo='deb http://nginx.org/packages/ubuntu/ trusty nginx' state=present

- name: install nginx web server and ensure its at the latest version
  apt: name=nginx state=latest force=yes
